title: Funes
description: Event sourcing meta-framework for Rails
url: "https://funes.org"
baseurl: ""

mixpanel_token: ""

# Build settings
markdown: kramdown
permalink: pretty

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
  - _config_env.yml
